from __future__ import annotations

import json
import subprocess
from fractions import Fraction
from pathlib import Path
from typing import Any, Mapping, Sequence
from xml.etree import ElementTree as ET

from .media import MediaToolError, has_audio_stream, require_media_tools
from .resolve_handoff import fcpx_time


def _safe_name(value: str) -> str:
    clean = "".join(character if character.isalnum() or character in " -_" else "-" for character in value)
    return clean.strip()[:100] or "Selects timeline"


def _source_times(item: Mapping[str, Any]) -> tuple[int, int]:
    in_us = int(item.get("in_us") if item.get("in_us") is not None else round(float(item["in_seconds"]) * 1_000_000))
    out_us = int(item.get("out_us") if item.get("out_us") is not None else round(float(item["out_seconds"]) * 1_000_000))
    return in_us, out_us


def validate_sequence(version: Mapping[str, Any]) -> list[Mapping[str, Any]]:
    items = list(version.get("items") or [])
    if not items:
        raise ValueError("Add at least one selected range before previewing or exporting.")
    for item in items:
        if item.get("source_status") != "ready":
            raise ValueError(f"{item.get('filename', 'A source')} is offline or unreadable.")
        source = Path(str(item["current_path"])).expanduser().resolve(strict=True)
        in_us, out_us = _source_times(item)
        if out_us <= in_us:
            raise ValueError(f"{source.name} has an invalid selected range.")
    return items


def build_fcpxml(
    version: Mapping[str, Any], *, project_name: str, orientation: str | None = None
) -> tuple[str, dict[str, Any]]:
    items = validate_sequence(version)
    orientation = orientation or str(version.get("orientation") or "landscape")
    root = ET.Element("fcpxml", {"version": "1.10"})
    resources = ET.SubElement(root, "resources")
    width, height = (2160, 3840) if orientation == "portrait" else (3840, 2160)
    ET.SubElement(resources, "format", {
        "id": "r1", "name": "Selects 4K 29.97", "frameDuration": "1001/30000s",
        "width": str(width), "height": str(height), "fieldOrder": "progressive", "colorSpace": "1-1-1 (Rec. 709)",
    })
    asset_ids: dict[str, str] = {}
    for index, item in enumerate(items, 2):
        source = Path(str(item["current_path"])).resolve(strict=True)
        asset_id = f"r{index}"
        asset_ids[str(item["id"])] = asset_id
        source_duration = Fraction(round(float(item["source_duration"]) * 1_000_000), 1_000_000)
        attributes = {
            "id": asset_id, "name": source.name, "start": "0s", "duration": fcpx_time(source_duration),
            "hasVideo": "1",
        }
        has_audio = item.get("has_audio")
        if "has_audio" in item and has_audio is None:
            try:
                has_audio = has_audio_stream(source)
            except MediaToolError:
                has_audio = False
        if bool(has_audio):
            attributes.update({"hasAudio": "1", "audioSources": "1", "audioChannels": "2", "audioRate": "48k"})
        asset = ET.SubElement(resources, "asset", attributes)
        ET.SubElement(asset, "media-rep", {
            "kind": "original-media", "src": source.as_uri(), "suggestedFilename": source.name,
        })

    library = ET.SubElement(root, "library", {"colorProcessing": "standard"})
    event = ET.SubElement(library, "event", {"name": f"{_safe_name(project_name)} · Selects"})
    project = ET.SubElement(event, "project", {"name": _safe_name(str(version.get("sequence_name") or "First cut"))})
    total = sum((Fraction(_source_times(item)[1] - _source_times(item)[0], 1_000_000) for item in items), Fraction(0))
    sequence = ET.SubElement(project, "sequence", {
        "format": "r1", "duration": fcpx_time(total), "tcStart": "0s", "tcFormat": "NDF",
        "audioLayout": "stereo", "audioRate": "48k",
    })
    ET.SubElement(sequence, "note").text = (
        "Generated by Selects from explicit source ranges. Originals are linked and untouched. "
        f"Project ID: {version.get('project_id', '')} | Sequence version ID: {version.get('id', '')}"
    )
    spine = ET.SubElement(sequence, "spine")
    offset = Fraction(0)
    manifest_items: list[dict[str, Any]] = []
    for position, item in enumerate(items, 1):
        in_us, out_us = _source_times(item)
        start = Fraction(in_us, 1_000_000)
        duration = Fraction(out_us - in_us, 1_000_000)
        clip = ET.SubElement(spine, "asset-clip", {
            "name": f"{position:02d}_{Path(str(item['current_path'])).stem}",
            "ref": asset_ids[str(item["id"])], "offset": fcpx_time(offset), "start": fcpx_time(start),
            "duration": fcpx_time(duration), "videoRole": "video", "audioRole": "dialogue",
        })
        note_parts = [str(item.get("comment") or "").strip()]
        if item.get("story_role"):
            note_parts.append(f"Story role: {item['story_role']}")
        note_parts.append(f"Audio intent: {item.get('audio_intent', 'undecided')}")
        note_parts.append(f"Selects source ID: {item.get('source_id', '')}")
        if item.get("source_fingerprint"):
            note_parts.append(f"Source fingerprint: {item['source_fingerprint']}")
        note_parts.append(f"Source rotation: {int(item.get('rotation') or 0)}°")
        note_parts.append(f"Effective timeline orientation: {orientation}")
        ET.SubElement(clip, "note").text = " | ".join(part for part in note_parts if part)
        metadata = ET.SubElement(clip, "metadata")
        for key, value in (
            ("com.selects.projectID", version.get("project_id") or ""),
            ("com.selects.sequenceVersionID", version.get("id") or ""),
            ("com.selects.sourceID", item.get("source_id") or ""),
            ("com.selects.sourceFingerprint", item.get("source_fingerprint") or ""),
            ("com.selects.sourceRotation", str(int(item.get("rotation") or 0))),
            ("com.selects.timelineOrientation", orientation),
        ):
            ET.SubElement(metadata, "md", {"key": key, "value": str(value)})
        manifest_items.append({
            "position": position, "selection_id": item["id"], "filename": item["filename"],
            "source_id": item.get("source_id"), "source_fingerprint": item.get("source_fingerprint"),
            "source_in": in_us / 1_000_000, "source_out": out_us / 1_000_000,
            "source_in_us": in_us,
            "source_out_us": out_us,
            "timeline_in": float(offset), "duration": float(duration), "comment": item.get("comment") or "",
            "duration_us": out_us - in_us,
            "rotation": int(item.get("rotation") or 0),
            "effective_orientation": orientation,
            "timing_mode": "VFR microseconds" if item.get("is_vfr") else "CFR frame-snapped",
            "audio_intent": item.get("audio_intent", "undecided"),
            "story_role": item.get("story_role"),
            "treatment": item.get("treatment") or {},
        })
        offset += duration
    ET.indent(root, space="  ")
    xml = '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE fcpxml>\n' + ET.tostring(
        root, encoding="unicode", short_empty_elements=True
    )
    return xml, {
        "format": "selects-handoff", "version": 3,
        "project_id": version.get("project_id"), "sequence_version_id": version.get("id"),
        "sequence_version": version.get("version"), "items": manifest_items,
        "duration": float(total), "timeline": {"width": width, "height": height, "fps": 30000 / 1001},
    }


def write_handoff(
    version: Mapping[str, Any], destination: Path, *, project_name: str, orientation: str | None = None
) -> dict[str, str]:
    destination.mkdir(parents=True, exist_ok=True)
    xml, manifest = build_fcpxml(version, project_name=project_name, orientation=orientation)
    stem = _safe_name(str(version.get("sequence_name") or "first-cut")).replace(" ", "-").lower()
    xml_path = destination / f"{stem}.fcpxml"
    manifest_path = destination / f"{stem}.json"
    xml_path.write_text(xml, encoding="utf-8")
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return {"fcpxml": str(xml_path), "manifest": str(manifest_path)}


def render_preview(version: Mapping[str, Any], destination: Path) -> Path:
    items = validate_sequence(version)
    destination.parent.mkdir(parents=True, exist_ok=True)
    ffmpeg, _ = require_media_tools()
    orientation = str(version.get("orientation") or "landscape")
    preview_width, preview_height = (480, 854) if orientation == "portrait" else (854, 480)
    command = [ffmpeg, "-v", "error", "-y"]
    filters: list[str] = []
    labels: list[str] = []
    for index, item in enumerate(items):
        in_us, out_us = _source_times(item)
        duration_us = out_us - in_us
        command.extend([
            "-ss", f"{in_us / 1_000_000:.6f}", "-t", f"{duration_us / 1_000_000:.6f}",
            "-i", str(Path(str(item["current_path"])).resolve(strict=True)),
        ])
        filters.append(
            f"[{index}:v]scale={preview_width}:{preview_height}:force_original_aspect_ratio=decrease,"
            f"pad={preview_width}:{preview_height}:(ow-iw)/2:(oh-ih)/2:black,fps=30,format=yuv420p,setsar=1[v{index}]"
        )
        source_path = Path(str(item["current_path"])).resolve(strict=True)
        use_audio = item.get("audio_intent") != "mute" and has_audio_stream(source_path)
        if use_audio:
            filters.append(
                f"[{index}:a]aresample=48000,aformat=sample_fmts=fltp:channel_layouts=stereo,asetpts=PTS-STARTPTS[a{index}]"
            )
        else:
            filters.append(
                f"anullsrc=r=48000:cl=stereo,atrim=duration={duration_us / 1_000_000:.6f},asetpts=PTS-STARTPTS[a{index}]"
            )
        labels.append(f"[v{index}][a{index}]")
    filters.append("".join(labels) + f"concat=n={len(items)}:v=1:a=1[outv][outa]")
    command.extend([
        "-filter_complex", ";".join(filters), "-map", "[outv]", "-map", "[outa]", "-c:v", "libx264",
        "-preset", "veryfast", "-crf", "27", "-c:a", "aac", "-b:a", "128k", "-movflags", "+faststart", str(destination),
    ])
    try:
        subprocess.run(command, check=True, capture_output=True, timeout=max(180, int(float(version["duration"]) * 8)))
    except subprocess.SubprocessError as exc:
        destination.unlink(missing_ok=True)
        raise MediaToolError("Could not render the sequence preview.") from exc
    return destination
