from __future__ import annotations

import json
import subprocess
from fractions import Fraction
from pathlib import Path
from typing import Any, Mapping, Sequence
from xml.etree import ElementTree as ET

from .media import MediaToolError, has_audio_stream, require_media_tools
from .resolve_handoff import fcpx_time, frame_duration, quantized_time


TIMELINE_FRAME_DURATION = Fraction(1_001, 30_000)


def _safe_name(value: str) -> str:
    clean = "".join(character if character.isalnum() or character in " -_" else "-" for character in value)
    return clean.strip()[:100] or "Selects timeline"


def validate_sequence(version: Mapping[str, Any]) -> list[Mapping[str, Any]]:
    items = list(version.get("items") or [])
    if not items:
        raise ValueError("Add at least one selected range before previewing or exporting.")
    for item in items:
        if item.get("source_status") != "ready":
            raise ValueError(f"{item.get('filename', 'A source')} is offline or unreadable.")
        source = Path(str(item["current_path"])).expanduser().resolve(strict=True)
        if float(item["out_seconds"]) <= float(item["in_seconds"]):
            raise ValueError(f"{source.name} has an invalid selected range.")
    return items


def build_fcpxml(
    version: Mapping[str, Any], *, project_name: str, orientation: str = "landscape"
) -> tuple[str, dict[str, Any]]:
    items = validate_sequence(version)
    root = ET.Element("fcpxml", {"version": "1.10"})
    resources = ET.SubElement(root, "resources")
    width, height = (2160, 3840) if orientation == "portrait" else (3840, 2160)
    ET.SubElement(resources, "format", {
        "id": "r1", "name": "Selects 4K 29.97", "frameDuration": "1001/30000s",
        "width": str(width), "height": str(height), "fieldOrder": "progressive", "colorSpace": "1-1-1 (Rec. 709)",
    })
    asset_ids: dict[str, str] = {}
    for index, item in enumerate(items, 2):
        source = Path(str(item["current_path"])).resolve(strict=True)
        asset_id = f"r{index}"
        asset_ids[str(item["id"])] = asset_id
        unit = frame_duration(float(item.get("fps") or 30.0))
        duration = quantized_time(float(item["source_duration"]), unit)
        attributes = {
            "id": asset_id, "name": source.name, "start": "0s", "duration": fcpx_time(duration),
            "hasVideo": "1",
        }
        has_audio = item.get("has_audio")
        if "has_audio" in item and has_audio is None:
            try:
                has_audio = has_audio_stream(source)
            except MediaToolError:
                has_audio = False
        if bool(has_audio):
            attributes.update({"hasAudio": "1", "audioSources": "1", "audioChannels": "2", "audioRate": "48k"})
        asset = ET.SubElement(resources, "asset", attributes)
        ET.SubElement(asset, "media-rep", {
            "kind": "original-media", "src": source.as_uri(), "suggestedFilename": source.name,
        })

    library = ET.SubElement(root, "library", {"colorProcessing": "standard"})
    event = ET.SubElement(library, "event", {"name": f"{_safe_name(project_name)} · Selects"})
    project = ET.SubElement(event, "project", {"name": _safe_name(str(version.get("sequence_name") or "First cut"))})
    total = sum(quantized_time(float(item["duration"]), TIMELINE_FRAME_DURATION) for item in items)
    sequence = ET.SubElement(project, "sequence", {
        "format": "r1", "duration": fcpx_time(total), "tcStart": "0s", "tcFormat": "NDF",
        "audioLayout": "stereo", "audioRate": "48k",
    })
    ET.SubElement(sequence, "note").text = (
        "Generated by Selects from explicit source ranges. Originals are linked and untouched."
    )
    spine = ET.SubElement(sequence, "spine")
    offset = Fraction(0)
    manifest_items: list[dict[str, Any]] = []
    for position, item in enumerate(items, 1):
        source_unit = frame_duration(float(item.get("fps") or 30.0))
        start = quantized_time(float(item["in_seconds"]), source_unit)
        duration = quantized_time(float(item["duration"]), TIMELINE_FRAME_DURATION)
        clip = ET.SubElement(spine, "asset-clip", {
            "name": f"{position:02d}_{Path(str(item['current_path'])).stem}",
            "ref": asset_ids[str(item["id"])], "offset": fcpx_time(offset), "start": fcpx_time(start),
            "duration": fcpx_time(duration), "videoRole": "video", "audioRole": "dialogue",
        })
        note_parts = [str(item.get("comment") or "").strip()]
        if item.get("story_role"):
            note_parts.append(f"Story role: {item['story_role']}")
        note_parts.append(f"Audio intent: {item.get('audio_intent', 'undecided')}")
        ET.SubElement(clip, "note").text = " | ".join(part for part in note_parts if part)
        manifest_items.append({
            "position": position, "selection_id": item["id"], "filename": item["filename"],
            "source_in": item["in_seconds"], "source_out": item["out_seconds"],
            "timeline_in": float(offset), "duration": float(duration), "comment": item.get("comment") or "",
        })
        offset += duration
    ET.indent(root, space="  ")
    xml = '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE fcpxml>\n' + ET.tostring(
        root, encoding="unicode", short_empty_elements=True
    )
    return xml, {
        "format": "selects-handoff", "version": 2, "items": manifest_items,
        "duration": float(total), "timeline": {"width": width, "height": height, "fps": 30000 / 1001},
    }


def write_handoff(
    version: Mapping[str, Any], destination: Path, *, project_name: str, orientation: str = "landscape"
) -> dict[str, str]:
    destination.mkdir(parents=True, exist_ok=True)
    xml, manifest = build_fcpxml(version, project_name=project_name, orientation=orientation)
    stem = _safe_name(str(version.get("sequence_name") or "first-cut")).replace(" ", "-").lower()
    xml_path = destination / f"{stem}.fcpxml"
    manifest_path = destination / f"{stem}.json"
    xml_path.write_text(xml, encoding="utf-8")
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return {"fcpxml": str(xml_path), "manifest": str(manifest_path)}


def render_preview(version: Mapping[str, Any], destination: Path) -> Path:
    items = validate_sequence(version)
    destination.parent.mkdir(parents=True, exist_ok=True)
    ffmpeg, _ = require_media_tools()
    command = [ffmpeg, "-v", "error", "-y"]
    filters: list[str] = []
    labels: list[str] = []
    for index, item in enumerate(items):
        command.extend([
            "-ss", f"{float(item['in_seconds']):.3f}", "-t", f"{float(item['duration']):.3f}",
            "-i", str(Path(str(item["current_path"])).resolve(strict=True)),
        ])
        filters.append(
            f"[{index}:v]scale=854:480:force_original_aspect_ratio=decrease,"
            f"pad=854:480:(ow-iw)/2:(oh-ih)/2:black,fps=30,format=yuv420p,setsar=1[v{index}]"
        )
        source_path = Path(str(item["current_path"])).resolve(strict=True)
        use_audio = item.get("audio_intent") != "mute" and has_audio_stream(source_path)
        if use_audio:
            filters.append(
                f"[{index}:a]aresample=48000,aformat=sample_fmts=fltp:channel_layouts=stereo,asetpts=PTS-STARTPTS[a{index}]"
            )
        else:
            filters.append(
                f"anullsrc=r=48000:cl=stereo,atrim=duration={float(item['duration']):.3f},asetpts=PTS-STARTPTS[a{index}]"
            )
        labels.append(f"[v{index}][a{index}]")
    filters.append("".join(labels) + f"concat=n={len(items)}:v=1:a=1[outv][outa]")
    command.extend([
        "-filter_complex", ";".join(filters), "-map", "[outv]", "-map", "[outa]", "-c:v", "libx264",
        "-preset", "veryfast", "-crf", "27", "-c:a", "aac", "-b:a", "128k", "-movflags", "+faststart", str(destination),
    ])
    try:
        subprocess.run(command, check=True, capture_output=True, timeout=max(180, int(float(version["duration"]) * 8)))
    except subprocess.SubprocessError as exc:
        destination.unlink(missing_ok=True)
        raise MediaToolError("Could not render the sequence preview.") from exc
    return destination
